### ISSUE TITLE
VIS anderes Aussehen nach Import

### ISSUE THREAD

**Issue by CaptainBalou** [Pittini/iobroker-LightControl#1]
Hallo Pittini,

ich bin auf dein LightControl Projekt gestoßen. Ich suche nach wie vor eine Lichtsteuerung die meine Anforderungen erfüllt, aber das scheint mit egal welcher man das versucht nicht zu passen. Dennoch schaue ich mir einfach verschiedene an um zu sehen was am besten passt. Von deiner VIS für HeatingControl bin ich bereits begeistert und somit muss ich LightControl natürlich testen. :-) Gibt es einen Thread in dem du dich mit Interesseirten darüber unterhälst oder soll man Fragen lieber hier stellen?

Funktionieren tut nach der ersten Installation mit den Lampen die ich heir verwende (Lightway von Aldi) noch nichts so wirklich, aber ich bin überzeugt, dass das eher ein Konfigurationsproblem ist. Ich teste noch ein wenig.

Was jedoch nicht weiter konfiguriert werden müsste ist die VIS die du zum Import bereitgestellt hast. Somit habe ich eine neue View angelegt und dort wie von dir beschrieben die Widgets importiert. Optisch hat das jedoch nciht mit dem zu tun was du als Screenshot mitgeliefert hast. Kannst du mir sagen weshalb das bei mir so anders aussieht?

![grafik](https://user-images.githubusercontent.com/17015872/111154617-b51a0480-8593-11eb-934c-a2a02a576f63.png)

Grüße
Marco

**Comment by Pittini** [comment]
Kannste hier machen oder im Forum, Link zum Thread steht in der ersten Zeile vom Skript.
Ja das Vis is klar, muß ich mal dazuschreiben. Ich verwende das [MaterialDesign von Uhula](https://github.com/Uhula/ioBroker-Material-Design-Style), wennde das nicht hast mußt viel anpassen. Schau Dir Uhulas Demoprojekt mal an.....und dann kopierste das Skript und CSS von da, nach Deinem Projekt, dann sollte es so aussehen wie aufm Screenshot, zumindest wennde die gleichen Farben im MD eingestellt hast.
Die Aldi Lampen sollten laufen, alle Basicfunktionen nutz ich hhier ja selber und soweit funktioniert das Skript auch.

**Comment by CaptainBalou** [comment]
Ah ich verstehe. Bin ein User ohne jegliches Know-How das irgendwie hin zu bekommen. Dein HeatingControl VIS zu importieren ging problemlos, aber das hier mit Uhula zu verheiraten - hehe, nein das wird nix werden. 
Diese Funktionen des Skriptes als Adapter zu haben wäre das Optimum. ;-) Denke aber das ist komplizierter als ich mir das vorstelle.
Ich expermentiere derweil mal noch mit dem Skript ohne das GUI.

Ich denke du kannst das issue dan schließen.

**Comment by Pittini** [comment]
Hey, wenn Du mein HeatingControl Vis in der normalvariante (nicht das simple) nutzt, da is das md von Uhula schon drin. Wenn Du da ne neue Seite anlegst und die Widgets importierst sollte das sofort laufen.

**Comment by CaptainBalou** [comment]
Das ist ein prima Vorschlag. Also bin ich direkt in die VIS, hab dort "new view" geklickt (pageLightControl) und auf dieser neuen Seite habe ich die Widgets importiert.

Aber so richtig erfolgreich war ich hier auch nicht. :-(

<img width="1632" alt="grafik" src="https://user-images.githubusercontent.com/17015872/111291289-56ae5e00-8647-11eb-8aae-4f07b8ff6845.png">

**Comment by Pittini** [comment]
Sieht doch schon ne Ecke besser aus. Was Dir fehlt is scheinbar der Farbwähler, der heißt "Colorpicker - RGBColor" und es fehlen Schaltflächen etc, da mußt (bei den Adaptern) die jqui-mfd Widgets installieren. Dann gugg ma nochmal wennde das hast.

**Comment by CaptainBalou** [comment]
Ah da muss man noch Dinge nachinstallieren. Ok das wusste ich nicht.
Zugegeben es hat sich etwas verändert.

<img width="1625" alt="grafik" src="https://user-images.githubusercontent.com/17015872/111299427-3767fe80-8650-11eb-84c9-d29bcea4b1a2.png">

Aber ist noch nicht alles so wie bei dir im Screenshot. Bei der Farbe kann ich durch Klick nichts auswählen, die Schieber haben den Text dahinter. Da stimmt noch was nicht.

**Comment by Pittini** [comment]
Ja hast Du denn überhaupt so viele Lichtgruppen? Weil wenn nicht, laufen natürlich die Vis DPs ins Leere, was auch die Schieber betrifft, da wird ein Wert in der Gruppe abgefragt und damit die Sichtbarkeit gesteuert, gibts die Gruppe nicht, gibts auch diesen Wert nicht. Du mußte überflüssiges entfernen, bzw. die Gruppen anpassen. Ich denke Du hast nur Gruppe 0, die wird nämlich ziemlich korrekt angezeigt. Also alle Tests nur mit Gruppe 0, also Flur Eg. machen.

**Comment by CaptainBalou** [comment]
Hallo Pittini,

das eigentlich verwirrende war für mich, dass ich in dem an/aus Schalter keinen Inhalt sehe. Aber das liegt daran weil der Hintergrund standardmäßig weiß ist. Es ist schon ein Inhalt drin, aber der ist nicht sichbar. Habe ein wenig gebraucht um herauszubekommen wie ich den Hintergrund ändere. Jetzt sieht das schon besser aus.

<img width="1632" alt="grafik" src="https://user-images.githubusercontent.com/17015872/111657687-f74d7b00-880b-11eb-9660-5ce8f41bf1ac.png">

Die nicht existenten Gruppen habe ich auch entfernt, dass es ein wenig hübscher aussieht.

Der Colorpicker funktioniert nun auch. Allerdings konnte ich den nicht klicken bis ich den Wert #FFFFFF einmalig aus dem DP Color entfernt hatte. Seither ist das problemlos.

Die Funktion mit den Lampen geht noch nicht wie gewünscht, aber das ist nichts was zu dieser Issue-Beschreibung passen würde.

Einieg Hinweise im Handbuch wären hilfreich um so Amateuren wie mir den Einstieg einfacher zu ermöglichen und so Profis wie dir Arbeit mit Fragen beantworten zu ersparen. :-)

Grüße
Marco

**Comment by Pittini** [comment]
Ja ich weis das die Doku hier noch verbesserungswürdig ist, aber solang das im Beta State ist und sich Sachen noch ändern können, halte ich das etwas knapper. Wenns fertig ist, wird das ausführlicher, siehste ja an den anderen Skripten.
Und gleich vorneweg bevor Fragen kommen, die "Alle" Gruppe ist noch nicht wirklich implementiert, das kommt ganz zum Ende.

**Comment by CaptainBalou** [comment]
Ich weiß, das ist alles Zeit was hier für so Doku drauf geht. Dachte eben nur weil ich dich jetzt hier mit so vermeintlichen "ist klar weshalb das nicht geht wenn er das Uhula Plugin nicht verwendet" Banalitäten aufgehalten habe. Ein Hinweis in der Doku wäre vielleicht schnell geschrieben und würde dem ein oder anderen schon helfen. Wenn ich wüsste wie ich es formulieren könnte würde ich nen PR machen. Aber da bin ich technisch zu wenig drin um das VIS Zeug richtig verstehen zu können.
