### ISSUE TITLE
AutoOffTimed -> Timeout wird nie gestoppt

### ISSUE THREAD

**Issue by Schmakus** [Pittini/iobroker-LightControl#10]
Hi, entweder sehe ich es nicht oder es ist tatsächlich so?!
In deinem Script wird das AutoOffTimed Timeout nie gestoppt, wenn eine neue Bewegung stattfindet. Es wir jedoch immer wieder die Funktion "AutoOffTimed()" aufgerufen. 
Festgestellt habe ich es, weil bei mir trotz Bewegung das Licht sporadisch ausgeht.

Muss im Controller bei "isMotion" noch ein "await clearAutoOffTimeouts(Group);" rein?

`case "isMotion":
            LightGroups[Group].isMotion = NewVal;
            if (!LightGroups[Group].powerCleaningLight) {
                if (LightGroups[Group].isMotion && LightGroups[Group].power) { //AutoOff Timer wird nach jeder Bewegung neugestartet
                    log("Controller: Motion detected, restarting AutoOff Timer for Group " + Group + " (" + LightGroups[Group].description + " )");
                    await AutoOffTimed(Group);
                };
                await AutoOnMotion(Group);
 };`

**Comment by Rudi-Ment** [comment]
Ist bei mir genauso. 
Licht geht immer wieder aus.
Lt Protokoll wird das Licht nachgetriggert.
Ich habe das Licht aktuell auf 1800 sek stehen, trotzdem gehts nach unbestimmter Zeit vordem aus. 
Trotz Bewegung.
