### ISSUE TITLE
Script läuft nicht

### ISSUE THREAD

**Issue by Ricox1975** [Pittini/iobroker-LightControl#11]
Mit Javascript v5.2.21 wird folgender Fehler ausgeworfen:
![image](https://user-images.githubusercontent.com/52467622/151698164-a1926eef-f7b6-4de9-9919-b347e172c5ef.png)

![image](https://user-images.githubusercontent.com/52467622/151698511-fac8a8cf-bc2e-40f0-9890-bd959399eefc.png)

**Comment by Pittini** [comment]
> Mit Javascript v5.2.21 wird folgender Fehler ausgeworfen: ![image](https://user-images.githubusercontent.com/52467622/151698164-a1926eef-f7b6-4de9-9919-b347e172c5ef.png)
> 
> ![image](https://user-images.githubusercontent.com/52467622/151698511-fac8a8cf-bc2e-40f0-9890-bd959399eefc.png)

Glaub nicht dass das n der JS Version liegt. Aufgrund der gemeldeten Fehlerzeilen, geh ich eher davon aus, dass bei Deiner Lampenkonfig was nicht passt, z.B. ne Klammer zuviel oder zuwenig, odern Komma. Kontrollier das mal, bzw. poste Deine Lampenkonfig mal.

**Comment by Schmakus** [comment]
BTW: JS Version 5.2.21 ist nicht im Stable. Aber wie Pittini schon sagt, liegt es kaum am Semikolon, sondern eher innerhalb der LightGroups.

**Comment by Ricox1975** [comment]
`const Version = "2.0.19" //vom 6.1.2022 - Skript um Lichter in Helligkeit, Farbe und Farbtemp global zu steuern - Git: https://github.com/Pittini/iobroker-LightControl - Forum: https://forum.iobroker.net/topic/36578/vorlage-lightcontrol

log("starting LightControl V." + Version);

const praefix = "javascript.0.LightControl2" // Skriptordner
const LuxSensor = 'zigbee.1.001788010649a76e.illuminance'; // Datenpunkt des globalen Luxsensors, wird verwendet wenn in der Gruppe kein gesonderter definiert wird
const IsPresenceDp = "0_userdata.0.Anwesenheit.niemand_hier"; // Datenpunkt für Anwesenheit (true/false)
const PresenceCountDp = ""; // Datenpunkt für Anwesenheitszähler
const logging = true; // Logging an/aus
const RampSteps = 10; //Wieviele Schritte zum dimmen? Bitte nicht zu hoch setzen, wird zwar smoother, kann aber zu timing Problemen führen wenn gleichzeitig eine kurze Zeit in den Objekten gewählt.

const minCt = 2500; //Regelbereich für Farbtemperatur in Kelvin für Adaptive Ct
const maxCt = 6500;//Regelbereich für Farbtemperatur in Kelvin für Adaptive Ct
const minBri = 10; //Mindesthelligkeit für AdaptiveBri

const LightGroups = {
    0: {
        description: "Draussen",
        lights: {
            0: {
                description: "StrahlerVorne",
                power: { oid: "zigbee.1.84fd27fffec8a159.state", onVal: true, offVal: false },
                bri: { oid: "zigbee.1.84fd27fffec8a159.brightness", minVal: 0, maxVal: 100, defaultVal: 100 },
                ct: { oid: "zigbee.1.84fd27fffec8a159.colortemp", minVal: 454, maxVal: 250 },
                sat: { oid: "zigbee.1.84fd27fffec8a159.saturation", minVal: 0, maxVal: 100 },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "zigbee.1.84fd27fffec8a159.color", type: "hex", default: "#FFFFFF" }
            },
            1: {
                description: "StrahlerHinten",
                power: { oid: "zigbee.1.680ae2fffe45777f.state", onVal: true, offVal: false },
                bri: { oid: "zigbee.1.680ae2fffe45777f.brightness", minVal: 0, maxVal: 100, defaultVal: 100 },
                ct: { oid: "zigbee.1.680ae2fffe45777f.colortemp", minVal: 454, maxVal: 250 },
                sat: { oid: "zigbee.1.680ae2fffe45777f.saturation", minVal: 0, maxVal: 100 },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "zigbee.1.680ae2fffe45777f.color", type: "hex", default: "#FFFFFF" }
            },
            2: {
                description: "CarportOben",
                power: { oid: "zigbee.1.0c4314fffe9afd63.state", onVal: true, offVal: false },
                bri: { oid: "", minVal: null, maxVal: null, defaultVal: null },
                ct: { oid: "", minVal: null, maxVal: null },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "", type: "", default: "" }
            },
            3: {
                description: "VordachLED",
                power: { oid: "zigbee.1.00124b0022fe219f.state", onVal: true, offVal: false },
                bri: { oid: "zigbee.1.00124b0022fe219f.brightness", minVal: 0, maxVal: 100, defaultVal: 100 },
                ct: { oid: "zigbee.1.00124b0022fe219f.colortemp", minVal: 6500, maxVal: 2700 },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "zigbee.1.00124b0022fe219f.color", type: "hex", default: "#FFFFFF" }
            },
            4: {
                description: "CarportLED",
                power: { oid: "zigbee.1.00124b0022fe2183.state", onVal: true, offVal: false },
                bri: { oid: "zigbee.1.00124b0022fe2183.brightness", minVal: 0, maxVal: 100, defaultVal: 100 },
                ct: { oid: "zigbee.1.00124b0022fe2183.colortemp", minVal: 6500, maxVal: 2700 },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "zigbee.1.00124b0022fe2183.color", type: "hex", default: "#FFFFFF" }
            }
            },
        sensors: {
            0: { id: 'zigbee.1.001788010649a76e.occupancy', motionVal: true, noMotionVal: false },
            1: { id: 'zigbee.1.001788010649ce68.occupancy', motionVal: true, noMotionVal: false },
            2: { id: 'zigbee.1.001788010649cd47.occupancy', motionVal: true, noMotionVal: false }
        }
    },
    1: {
        description: "Treppe",
        lights: {
            0: {
                description: "Deckenlicht",
                power: { oid: "yeelight-2.0.Rico_Treppe.control.power", onVal: true, offVal: false },
                bri: { oid: "yeelight-2.0.Rico_Treppe.control.active_bright", minVal: 0, maxVal: 100, defaultVal: 50 },
                ct: { oid: "yeelight-2.0.Rico_Treppe.control.ct", minVal: 6500, maxVal: 2700 },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "yeelight-2.0.Rico_Treppe.control.moon_mode", whiteModeVal: false, colorModeVal: true },
                color: { oid: "", type: "", default: "" }
            },
            1: {
                description: "Wandleuchte",
                power: { oid: "zigbee.1.0017880103c6e26f.state", onVal: true, offVal: false },
                bri: { oid: "zigbee.1.0017880103c6e26f.brightness", minVal: 0, maxVal: 100, defaultVal: 50 },
                ct: { oid: "zigbee.1.0017880103c6e26f.colortemp", minVal: 450, maxVal: 250 },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "", type: "", default: "" }
            },
                       
        sensors: {
            0: { id: 'zigbee.1.00158d0004514d87.occupancy', motionVal: true, noMotionVal: false },
            1: { id: 'zigbee.1.00158d000451951f.occupancy', motionVal: true, noMotionVal: false },
               }
    },
    2: {
        description: "Rico Flur unten",
        lights: {
            0: {
                description: "Wandlampe",
                power: { oid: "zigbee.1.588e81fffeee01fe.state", onVal: true, offVal: false },
                bri: { oid: "zigbee.1.588e81fffeee01fe.brightness", minVal: 0, maxVal: 100, defaultVal: 100 },
                ct: { oid: "zigbee.1.588e81fffeee01fe.colortemp", minVal: 454, maxVal: 250 },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "", type: "", default: "" }
            }
        },
        sensors: {
            0: { id: 'zigbee.1.001788010b0a0265.occupancy', motionVal: true, noMotionVal: false }
        }
    },
    3: {
        description: "Ankleide",
        lights: {
            0: {
                description: "Ankleide hinten",
                power: { oid: "zigbee.1.842e14fffe07416a.state", onVal: true, offVal: false },
                bri: { oid: "zzigbee.1.842e14fffe07416a.brightness", minVal: 0, maxVal: 100, defaultVal: 100 },
                ct: { oid: "zigbee.1.842e14fffe07416a.colortemp", minVal: 450, maxVal: 150 },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "", type: "", default: "", warmWhiteColor: "", dayLightColor: "" }
            },
            1: {
                description: "Ankleide vorne",
                power: { oid: "zigbee.1.588e81fffefcd42f.state", onVal: true, offVal: false },
                bri: { oid: "zigbee.1.588e81fffefcd42f.brightness", minVal: 0, maxVal: 100, defaultVal: 50 },
                ct: { oid: "zigbee.1.588e81fffefcd42f.colortemp", minVal: 454, maxVal: 150 },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "", type: "", default: "", warmWhiteColor: "", dayLightColor: "" }
            }
        },
        sensors: {
            0: { id: 'zigbee.1.001788010b09fdfc.occupancy', motionVal: true, noMotionVal: false },
               }
    },
    4: {
        description: "Bad R",
        lights: {
            0: {
                description: "Spiegelschrank",
                power: { oid: "alias.0.Licht.Badlicht_Rico.SET", onVal: true, offVal: false },
                bri: { oid: "", minVal: null, maxVal: null, defaultVal: null },
                ct: { oid: "", minVal: null, maxVal: null },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "", type: "", default: "" }
            }
        },
        sensors: {        
        }
    },
    5: {
        description: "Wohnzimmer R",
        lights: {
            0: {
                description: "Stehlampe",
                power: { oid: "alias.0.Licht.Rico_Wohnzimmer_Stehlampe.SET", onVal: true, offVal: false },
                bri: { oid: "", minVal: null, maxVal: null, defaultVal: null },
                ct: { oid: "", minVal: null, maxVal: null },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "", type: "", default: "" }
            },
            1: {
                description: "DeckenLED",
                power: { oid: "alias.0.Licht.Rico_Wohnzimmer.SET", onVal: true, offVal: false },
                bri: { oid: "", minVal: null, maxVal: null, defaultVal: null },
                ct: { oid: "", minVal: null, maxVal: null },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "", type: "", default: "" }
            }
        },
        sensors: {}
    },
    6: {
        description: "Schlafzimmer R",
        lights: {
            0: {
                description: "Nachttischlampe",
                power: { oid: "yeelight-2.0.Nachtlicht.control.power", onVal: true, offVal: false },
                bri: { oid: "yeelight-2.0.Nachtlicht.control.active_bright", minVal: 0, maxVal: 100, defaultVal: 100 },
                ct: { oid: "yeelight-2.0.Nachtlicht.control.ct", minVal: 454, maxVal: 250 },
                sat: { oid: "yeelight-2.0.Nachtlicht.control.sat", minVal: 10, maxVal: 100 },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "yeelight-2.0.Nachtlicht.control.rgb", type: "rgb", default: "16750592" }
            },
            sensors: {}
    },
    7: {
        description: "Küche",
        lights: {
            0: {
                description: "Schranklicht",
                power: { oid: "alias.0.Licht.Küche_Schranklicht.SET", onVal: true, offVal: false },
                bri: { oid: "", minVal: 0, maxVal: null, defaultVal: null },
                ct: { oid: "", minVal: null, maxVal: null },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "", type: "", default: "" }
            },
            1: {
                description: "Tischlicht",
                power: { oid: "alias.0.Licht.Küche_Tischlicht.SET", onVal: true, offVal: false },
                bri: { oid: "", minVal: null, maxVal: null, defaultVal: null },
                ct: { oid: "", minVal: null, maxVal: null },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "", type: "", default: "" }
            }
        },
        sensors: {}  
        },
    8: {
        description: "Heizraum",
        lights: {
            0: {
                description: "Deckenlicht",
                power: { oid: "yeelight-2.0.Heizraum.control.power", onVal: true, offVal: false },
                bri: { oid: "yeelight-2.0.Heizraum.control.active_bright", minVal: 0, maxVal: 100, defaultVal: 50 },
                ct: { oid: "yeelight-2.0.Heizraum.control.ct", minVal: 6500, maxVal: 1500 },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "yeelight-2.0.Heizraum.control.moon_mode", whiteModeVal: false, colorModeVal: true },
                color: { oid: "", type: "", default: "" }
            }
        },
        sensors: {}
    },
    9: {
        description: "Gartenhaus Aussenbeleuchtung",
        lights: {
            0: {
                description: "LED Streifen",
                power: { oid: "sonoff.0.Aussenlicht Gartenhaus.POWER", onVal: true, offVal: false },
                bri: { oid: "", minVal: null, maxVal: null, defaultVal: null },
                ct: { oid: "", minVal: null, maxVal: null },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "", type: "", default: "" }
            }
        },
        sensors: {
            0: { id: 'zigbee.1.001788010649f070.occupancy', motionVal: true, noMotionVal: false }
        }
    },
    10: {
        description: "Sauna",
        lights: {
            0: {
                description: "LED Streifen",
                power: { oid: "zigbee.1.cc86ecfffe5692c0.state", onVal: true, offVal: false },
                bri: { oid: "zigbee.1.cc86ecfffe5692c0.brightness", minVal: 0, maxVal: 100, defaultVal: 100 },
                ct: { oid: "", minVal: null, maxVal: null },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "", type: "", default: "" }
            }
        },
    11: {
        description: "HG Flur",
        lights: {
            0: {
                description: "Glaswand",
                power: { oid: "zigbee.1.60a423fffeae6a46.state", onVal: true, offVal: false },
                bri: { oid: "", minVal: null, maxVal: null, defaultVal: null },
                ct: { oid: "", minVal: null, maxVal: null },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "", type: "", default: "" }
            },
            1: {
                description: "DeckenLED",
                power: { oid: "zigbee.1.680ae2fffe3a2d69.state", onVal: true, offVal: false },
                bri: { oid: "", minVal: null, maxVal: null, defaultVal: null },
                ct: { oid: "", minVal: null, maxVal: null },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "", type: "", default: "" }
            }
        },
        sensors: {

        }
    }

};`

**Comment by Ricox1975** [comment]
`const Version = "2.0.19" //vom 6.1.2022 - Skript um Lichter in Helligkeit, Farbe und Farbtemp global zu steuern - Git: https://github.com/Pittini/iobroker-LightControl - Forum: https://forum.iobroker.net/topic/36578/vorlage-lightcontrol

log("starting LightControl V." + Version);

const praefix = "javascript.0.LightControl2" // Skriptordner
const LuxSensor = 'zigbee.1.001788010649a76e.illuminance'; // Datenpunkt des globalen Luxsensors, wird verwendet wenn in der Gruppe kein gesonderter definiert wird
const IsPresenceDp = "0_userdata.0.Anwesenheit.niemand_hier"; // Datenpunkt für Anwesenheit (true/false)
const PresenceCountDp = ""; // Datenpunkt für Anwesenheitszähler
const logging = false; // Logging an/aus
const RampSteps = 10; //Wieviele Schritte zum dimmen? Bitte nicht zu hoch setzen, wird zwar smoother, kann aber zu timing Problemen führen wenn gleichzeitig eine kurze Zeit in den Objekten gewählt.

const minCt = 2500; //Regelbereich für Farbtemperatur in Kelvin für Adaptive Ct
const maxCt = 6500;//Regelbereich für Farbtemperatur in Kelvin für Adaptive Ct
const minBri = 10; //Mindesthelligkeit für AdaptiveBri

const LightGroups = {
    0: {
        description: "Draussen",
        lights: {
            0: {
                description: "StrahlerVorne",
                power: { oid: "zigbee.1.84fd27fffec8a159.state", onVal: true, offVal: false },
                bri: { oid: "zigbee.1.84fd27fffec8a159.brightness", minVal: 0, maxVal: 100, defaultVal: 100 },
                ct: { oid: "zigbee.1.84fd27fffec8a159.colortemp", minVal: 454, maxVal: 250 },
                sat: { oid: "zigbee.1.84fd27fffec8a159.saturation", minVal: 0, maxVal: 100 },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "zigbee.1.84fd27fffec8a159.color", type: "hex", default: "#FFFFFF" }
            },
            1: {
                description: "StrahlerHinten",
                power: { oid: "zigbee.1.680ae2fffe45777f.state", onVal: true, offVal: false },
                bri: { oid: "zigbee.1.680ae2fffe45777f.brightness", minVal: 0, maxVal: 100, defaultVal: 100 },
                ct: { oid: "zigbee.1.680ae2fffe45777f.colortemp", minVal: 454, maxVal: 250 },
                sat: { oid: "zigbee.1.680ae2fffe45777f.saturation", minVal: 0, maxVal: 100 },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "zigbee.1.680ae2fffe45777f.color", type: "hex", default: "#FFFFFF" }
            },
            2: {
                description: "CarportOben",
                power: { oid: "zigbee.1.0c4314fffe9afd63.state", onVal: true, offVal: false },
                bri: { oid: "", minVal: null, maxVal: null, defaultVal: null },
                ct: { oid: "", minVal: null, maxVal: null },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "", type: "", default: "" }
            },
            3: {
                description: "VordachLED",
                power: { oid: "zigbee.1.00124b0022fe219f.state", onVal: true, offVal: false },
                bri: { oid: "zigbee.1.00124b0022fe219f.brightness", minVal: 0, maxVal: 100, defaultVal: 100 },
                ct: { oid: "zigbee.1.00124b0022fe219f.colortemp", minVal: 6500, maxVal: 2700 },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "zigbee.1.00124b0022fe219f.color", type: "hex", default: "#FFFFFF" }
            },
            4: {
                description: "CarportLED",
                power: { oid: "zigbee.1.00124b0022fe2183.state", onVal: true, offVal: false },
                bri: { oid: "zigbee.1.00124b0022fe2183.brightness", minVal: 0, maxVal: 100, defaultVal: 100 },
                ct: { oid: "zigbee.1.00124b0022fe2183.colortemp", minVal: 6500, maxVal: 2700 },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "zigbee.1.00124b0022fe2183.color", type: "hex", default: "#FFFFFF" }
            }
            },
        sensors: {
            0: { id: 'zigbee.1.001788010649a76e.occupancy', motionVal: true, noMotionVal: false },
            1: { id: 'zigbee.1.001788010649ce68.occupancy', motionVal: true, noMotionVal: false },
            2: { id: 'zigbee.1.001788010649cd47.occupancy', motionVal: true, noMotionVal: false }
        }
    },
    1: {
        description: "Treppe",
        lights: {
            0: {
                description: "Deckenlicht",
                power: { oid: "yeelight-2.0.Rico_Treppe.control.power", onVal: true, offVal: false },
                bri: { oid: "yeelight-2.0.Rico_Treppe.control.active_bright", minVal: 0, maxVal: 100, defaultVal: 50 },
                ct: { oid: "yeelight-2.0.Rico_Treppe.control.ct", minVal: 6500, maxVal: 2700 },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "yeelight-2.0.Rico_Treppe.control.moon_mode", whiteModeVal: false, colorModeVal: true },
                color: { oid: "", type: "", default: "" }
            },
            1: {
                description: "Wandleuchte",
                power: { oid: "zigbee.1.0017880103c6e26f.state", onVal: true, offVal: false },
                bri: { oid: "zigbee.1.0017880103c6e26f.brightness", minVal: 0, maxVal: 100, defaultVal: 50 },
                ct: { oid: "zigbee.1.0017880103c6e26f.colortemp", minVal: 450, maxVal: 250 },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "", type: "", default: "" }
            },
                       
        sensors: {
            0: { id: 'zigbee.1.00158d0004514d87.occupancy', motionVal: true, noMotionVal: false },
            1: { id: 'zigbee.1.00158d000451951f.occupancy', motionVal: true, noMotionVal: false }
               }
    },
    2: {
        description: "Rico Flur unten",
        lights: {
            0: {
                description: "Wandlampe",
                power: { oid: "zigbee.1.588e81fffeee01fe.state", onVal: true, offVal: false },
                bri: { oid: "zigbee.1.588e81fffeee01fe.brightness", minVal: 0, maxVal: 100, defaultVal: 100 },
                ct: { oid: "zigbee.1.588e81fffeee01fe.colortemp", minVal: 454, maxVal: 250 },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "", type: "", default: "" }
            }
        },
        sensors: {
            0: { id: 'zigbee.1.001788010b0a0265.occupancy', motionVal: true, noMotionVal: false }
        }
    },
    3: {
        description: "Ankleide",
        lights: {
            0: {
                description: "Ankleide hinten",
                power: { oid: "zigbee.1.842e14fffe07416a.state", onVal: true, offVal: false },
                bri: { oid: "zzigbee.1.842e14fffe07416a.brightness", minVal: 0, maxVal: 100, defaultVal: 100 },
                ct: { oid: "zigbee.1.842e14fffe07416a.colortemp", minVal: 450, maxVal: 150 },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "", type: "", default: "", warmWhiteColor: "", dayLightColor: "" }
            },
            1: {
                description: "Ankleide vorne",
                power: { oid: "zigbee.1.588e81fffefcd42f.state", onVal: true, offVal: false },
                bri: { oid: "zigbee.1.588e81fffefcd42f.brightness", minVal: 0, maxVal: 100, defaultVal: 50 },
                ct: { oid: "zigbee.1.588e81fffefcd42f.colortemp", minVal: 454, maxVal: 150 },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "", type: "", default: "", warmWhiteColor: "", dayLightColor: "" }
            }
        },
        sensors: {
            0: { id: 'zigbee.1.001788010b09fdfc.occupancy', motionVal: true, noMotionVal: false }
               }
    },
    4: {
        description: "Bad Rico",
        lights: {
            0: {
                description: "Spiegelschrank",
                power: { oid: "zigbee.1.0c4314fffe9af947.state", onVal: true, offVal: false },
                bri: { oid: "", minVal: null, maxVal: null, defaultVal: null },
                ct: { oid: "", minVal: null, maxVal: null },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "", type: "", default: "" }
            }
        },
        sensors: {}       
        }
    },
    5: {
        description: "Wohnzimmer Rico",
        lights: {
            0: {
                description: "Stehlampe",
                power: { oid: "zigbee.1.588e81fffed39529.state", onVal: true, offVal: false },
                bri: { oid: "", minVal: null, maxVal: null, defaultVal: null },
                ct: { oid: "", minVal: null, maxVal: null },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "", type: "", default: "" }
            },
            1: {
                description: "DeckenLED",
                power: { oid: "zigbee.1.84fd27fffe3b1ede.state", onVal: true, offVal: false },
                bri: { oid: "", minVal: null, maxVal: null, defaultVal: null },
                ct: { oid: "", minVal: null, maxVal: null },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "", type: "", default: "" }
            }
        },
        sensors: {}
    },
    6: {
        description: "Schlafzimmer Rico",
        lights: {
            0: {
                description: "Nachttischlampe",
                power: { oid: "yeelight-2.0.Nachtlicht.control.power", onVal: true, offVal: false },
                bri: { oid: "yeelight-2.0.Nachtlicht.control.active_bright", minVal: 0, maxVal: 100, defaultVal: 100 },
                ct: { oid: "yeelight-2.0.Nachtlicht.control.ct", minVal: 454, maxVal: 250 },
                sat: { oid: "yeelight-2.0.Nachtlicht.control.sat", minVal: 10, maxVal: 100 },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "yeelight-2.0.Nachtlicht.control.rgb", type: "rgb", default: "16750592" }
            },
            sensors: {}
    },
    7: {
        description: "Küche",
        lights: {
            0: {
                description: "Schranklicht",
                power: { oid: "zigbee.1.60a423fffeae69e3.state", onVal: true, offVal: false },
                bri: { oid: "", minVal: 0, maxVal: null, defaultVal: null },
                ct: { oid: "", minVal: null, maxVal: null },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "", type: "", default: "" }
            },
            1: {
                description: "Tischlicht",
                power: { oid: "zigbee.1.0c4314fffe9afe7e.state", onVal: true, offVal: false },
                bri: { oid: "", minVal: null, maxVal: null, defaultVal: null },
                ct: { oid: "", minVal: null, maxVal: null },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "", type: "", default: "" }
            }
        },
        sensors: {}  
        },
    8: {
        description: "Heizraum",
        lights: {
            0: {
                description: "Deckenlicht",
                power: { oid: "yeelight-2.0.Heizraum.control.power", onVal: true, offVal: false },
                bri: { oid: "yeelight-2.0.Heizraum.control.active_bright", minVal: 0, maxVal: 100, defaultVal: 50 },
                ct: { oid: "yeelight-2.0.Heizraum.control.ct", minVal: 6500, maxVal: 1500 },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "yeelight-2.0.Heizraum.control.moon_mode", whiteModeVal: false, colorModeVal: true },
                color: { oid: "", type: "", default: "" }
            }
        },
        sensors: {}
    },
    9: {
        description: "Gartenhaus Aussenbeleuchtung",
        lights: {
            0: {
                description: "LED Streifen",
                power: { oid: "sonoff.0.Aussenlicht Gartenhaus.POWER", onVal: true, offVal: false },
                bri: { oid: "", minVal: null, maxVal: null, defaultVal: null },
                ct: { oid: "", minVal: null, maxVal: null },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "", type: "", default: "" }
            }
        },
        sensors: {
            0: { id: 'zigbee.1.001788010649f070.occupancy', motionVal: true, noMotionVal: false }
        }
    },
    10: {
        description: "Sauna",
        lights: {
            0: {
                description: "LED Streifen",
                power: { oid: "zigbee.1.cc86ecfffe5692c0.state", onVal: true, offVal: false },
                bri: { oid: "zigbee.1.cc86ecfffe5692c0.brightness", minVal: 0, maxVal: 100, defaultVal: 100 },
                ct: { oid: "", minVal: null, maxVal: null },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "", type: "", default: "" }
            }
        },
    11: {
        description: "Helmut Flur",
        lights: {
            0: {
                description: "Glaswand",
                power: { oid: "zigbee.1.60a423fffeae6a46.state", onVal: true, offVal: false },
                bri: { oid: "", minVal: null, maxVal: null, defaultVal: null },
                ct: { oid: "", minVal: null, maxVal: null },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "", type: "", default: "" }
            },
            1: {
                description: "DeckenLED",
                power: { oid: "zigbee.1.680ae2fffe3a2d69.state", onVal: true, offVal: false },
                bri: { oid: "", minVal: null, maxVal: null, defaultVal: null },
                ct: { oid: "", minVal: null, maxVal: null },
                sat: { oid: "", minVal: null, maxVal: null },
                modeswitch: { oid: "", whiteModeVal: null, colorModeVal: null },
                color: { oid: "", type: "", default: "" }
            }
        },
        sensors: {

        }
    }
};
`

**Comment by Schmakus** [comment]
Verwende bitte den "Code" tag zum Posten des Codes. Das lässt sich so nicht lesen.

**Comment by Pittini** [comment]
> Habe noch einige Komas und Klammern berichtigt, aber immer noch der selbe Fehler [PittiniLight.txt](https://github.com/Pittini/iobroker-LightControl/files/7966727/PittiniLight.txt) .

Wenn ich Deine Json in nen Json Viewer werf, sagt der sofort kein gültiges JSON. Also ist, wie vermutet, da dran was faul.
Mußt halt mal auf die Suche gehen, ich empfehle mit einer Lampengruppe anzufangen und dann nach und nach weitere hinzufügen bis der Fehler kommt, dann weiste wo er is.

**Comment by Ricox1975** [comment]
Es fehlten zwei Klammern...
