### ISSUE TITLE
Wrong Datapoint-Name or wrong link in VIS

### ISSUE THREAD

**Issue by Rudi-Ment** [Pittini/iobroker-LightControl#12]
Hi.
The Datapoint for NoAutoOnWhenMotoin is in the Script named "NoAutoOffWhenMotion but in the VIS you have "noAutoOffWhenMotion".
The capital at the beginnig is the reason the the datapoint gets not update from the VIS
I think you know what i mean.
![datapoint_objects](https://user-images.githubusercontent.com/43185860/151945817-40e123d4-e2e5-4fa5-95ab-86a9e6d29a1a.png)
![datapoint_vis](https://user-images.githubusercontent.com/43185860/151945820-f60ea231-f950-4807-80d4-ead12d27be2a.png)

**Comment by Schmakus** [comment]
fixed
