### ISSUE TITLE
Shelly RGBW steuern iot Google Home

### ISSUE THREAD

**Issue by kilian-f-za** [Pittini/iobroker-LightControl#14]
Hallo, ich habe eine Shelly Duo Lampe und möchte die ansteuern. Soweit funktioniert alles, ich habe die Datenpunkte im Script eingegeben (color,bri,power,modeswitch). Die Lampe hat im Shelly Adapter einen rgbw Wert und keinen rgb Wert. Ich bekomme den Wechsel zwischen color und white nicht hin. Was muss ich eintragen, dass er bei einem Weißwert den modeswitch auf white stellt. 

Im iot Adapter habe ich bei Google Home ebenfalls (power,bri,color) eingetragen. Die color Werte werden geändert aber es kommen auch da keine Weißwerte an. Muss ich im Script ct und bri vlt noch angeben? Kann mir da jemand helfen?

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/87258544/193068318-a28aa5c4-811c-41be-882d-2ce733ca64ea.png">
<img width="806" alt="image" src="https://user-images.githubusercontent.com/87258544/193068423-52086127-b58f-4993-ab45-69bd1831b032.png">

**Comment by Pittini** [comment]
Wird vermutlich nicht klappen, bist der erste mit rgbw in der Form. Wie sehen den die Werte da aus? Und auf jeden Fall sollteste nen default bei color eintragen.

**Comment by kilian-f-za** [comment]
Das habe ich an Datenpunkten. 
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/87258544/193079515-4fef37b6-31d9-4bd9-9d70-7da0b688bff7.png">

Die Farbwerte (rgbw) können nur eingestellt werden, wenn mode auf color steht. Dann kann die Helligkeit über gain gesteuert werden
Bei weißem LIcht muss der mode auf white gestellt werden und dann kann über temp die Farbtemperatur eingestellt werden und über brightness die Helligkeit. Somit gibt es zwei DP für die Helligkeit, finde ich total ungünstig. 

Bei dem rgbw habe ich es noch nicht hinbekommen ein z.b. warmweiß einzustellen, dies habe ich nur über temp hinbekommen.

**Comment by Pittini** [comment]
> Bei dem rgbw habe ich es noch nicht hinbekommen ein z.b. warmweiß einzustellen, dies habe ich nur über temp hinbekommen.

Ändert sich denn der rgbw Wert nicht wenn Du via temp einstellst? Weil dann hättest ja Beispielwerte. Ansonsten, das ganze sieht mir so verquer aus, da müßte man die ganze Skriptlogik umbauen um das (vielleicht) hinzukriegen und dafür hab ich definitiv aktuell keine Zeit.
Meine einzige Lampe, welche überhaupt so ne Umschaltung hat, sieht im Skript so aus:
![2022-09-29 19_09_19-javascript - Iobroker](https://user-images.githubusercontent.com/51408942/193096031-f285683f-ee1e-41bf-8b26-528f12cab3f2.png)

und im Objektbaum so:

![2022-09-29 19_13_01-objects - Iobroker](https://user-images.githubusercontent.com/51408942/193097030-ef499172-233a-40a0-92cf-19323997d374.png)

Da klappt das auch mit der modeswitch umschaltung.

**Comment by kilian-f-za** [comment]
Wenn ich die temp ändere, bleibt der rgbw Wert gleich. Ist das bei dir auch so? Kann ich dann auch die Datenpunkte bei mir so eintragen und schauen ob er umschaltet? Wann schaltet das Script auf white oder color?

Hast du eine Idee wie ich es mit gain und brightness mache? Ein kleines Script welches gain und brightness immeer auf den gleichen Wert setzt?

**Comment by Pittini** [comment]
> Wenn ich die temp ändere, bleibt der rgbw Wert gleich. Ist das bei dir auch so? 

nein, bei mir werden die anderen Werte aktualisiert.

Kann ich dann auch die Datenpunkte bei mir so eintragen und schauen ob er umschaltet? Wann schaltet das Script auf white oder color?
Wenn ein Farbwert von #FFFFFF erkannt wird, schaltet das Skript auf white, ansonsten auf color.

> Hast du eine Idee wie ich es mit gain und brightness mache? Ein kleines Script welches gain und brightness immeer auf den gleichen Wert setzt?

Leider keine Idee.

**Comment by kilian-f-za** [comment]
Hallo, ich habe es jetzt nochmal probiert. Ich habe ein kleines blockly geschrieben welches die brightness und gain immer auf den gleichen Wert setzt. Außerdem habe ich zwei Trigger die auf color und temp regieren und dann den Mode entsprechend umschalten. Dies funktioniert auch super wenn ich die Datenpunkte im shelly.0. verwende. Wenn ich jetzt die Datenpunkte von shelly.0. in das Lightcontrol Script eintrage (siehe Bild oben) dann schaltet die Lampe nicht richtig. Die Farben werden erst übernommen wenn ich den Farbwert zweimal setze. Es ist ein sehr komisches Verhalten. Manchmal zeigt die Lampe auch eine ganz andere Farbe. Woran könnte das liegen? Ich habe es jetzt erstmal über die Datenpunkte direkt mit iot Google Home verknüpft und es funktioniert, aber trotzdem würde ich es gerne über Lightcontrol laufen lassen.

**Comment by Pittini** [comment]
> Es ist ein sehr komisches Verhalten.

Komische Verhaltenweisen sind oftmals timing Probleme und/oder falsche ack Werte.

**Comment by kilian-f-za** [comment]
Ok, also meinst du stimmt noch etwas nicht?

**Comment by Pittini** [comment]
> Ok, also meinst du stimmt noch etwas nicht?

Das is ja mal sicher, sonst würds ja funktionieren. Mach mal ne Verzögerung von 100ms rein beim setzten der Werte in Deinem Skript und gugg obs was hilft.
