### ISSUE TITLE
Einrichtung des Adapters

### ISSUE THREAD

**Issue by Trunks1982** [Pittini/iobroker-LightControl#17]
Hi ich habe mir gerade deinen Adapter in Iobroker installiert, wie ist jetzt das weitere Vorgehen um eine Lampe zb im Schlafzimmer zu steuern?

**Comment by Schmakus** [comment]
Dies hier ist ein Script.
Alle Infos zum Adapter hier: [https://github.com/Schmakus/ioBroker.lightcontrol](https://github.com/Schmakus/ioBroker.lightcontrol)

**Comment by Trunks1982** [comment]
Ah super deinen Hatte ich nicht gefunden bzw gesehen.
