### ISSUE TITLE
Helligkeit direkt -> falsche Berechnung

### ISSUE THREAD

**Issue by Schmakus** [Pittini/iobroker-LightControl#5]
Hi Pittini,
habe ich einen Denkfehler oder ist es tatsächlich so?Ich setzte die Helligkeit mit deinem Datenpunkt, jedoch werden die Leuchten mit einem falsch berechneten Wert gesetzt.

Beispiel: Helligkeit 70% -> Helligkeit Leuchten 49%
Deine Formel im Script: Helligkeit / 100 * DefaultBrightness 

Wieso die Multiplikation mit Default-Value?

![Xnip2021-12-26_10-46-51](https://user-images.githubusercontent.com/8231359/147404644-dfdebf16-6636-4d69-b068-9bd13906fd08.jpg)

**Comment by Pittini** [comment]
Works as designed. Sinn (aus der Anleitung):
_Möglichkeit der Zuweisung von defaultwerten zu jedem Leuchtmittel (gleiche Helligkeit trotz unterschiedlich leistungsstarker Leuchtmittel)_

**Comment by Schmakus** [comment]
Wer lesen kann ist klar im Vorteil. 😂
